source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.9'
# Use postgresql as the database for Active Record
gem 'pg'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
#gem 'therubyracer',  platforms: :ruby

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring'

# Auth
gem 'devise'
gem "cancan"
gem 'role_model'
gem 'omniauth-facebook'

gem 'geokit-rails'

gem 'google-analytics-rails'

#https://github.com/kjvarga/sitemap_generator
#gem 'instagram'#, :git => 'git://github.com/sealabcore/instagram-ruby-gem.git'
gem 'carrierwave'

gem 'forgery', '0.6.0'

gem 'rspec-rails', '~> 3.0'